# Generated by Django 3.1.3 on 2020-11-19 07:37

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Painting', models.ImageField(upload_to=gallery.models.get_file_path)),
                ('PaintingName', models.CharField(max_length=255)),
                ('PaintingDesc', models.TextField()),
                ('PaintingCat', models.CharField(max_length=255)),
            ],
        ),
    ]
