# Generated by Django 3.1.3 on 2020-11-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paint',
            new_name='Painting',
        ),
    ]
