# Generated by Django 3.1.3 on 2020-11-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201119_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
