# Generated by Django 3.1.3 on 2020-11-19 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_delete_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Painting', models.ImageField(upload_to=gallery.models.get_file_path)),
                ('PaintingName', models.CharField(max_length=255)),
                ('PaintingDesc', models.TextField()),
                ('PaintingCat', models.CharField(max_length=255)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
